.if t .ds TX "T\h'-.15m'\v'.2v'E\v'-.2v'\h'-.12m'X
.if t .ds LX L\v'-.22m'A\v'.22m'T\h'-.1667m'\v'.22m'E\h'-.125m'\v'-.22m'X
.TH MENDEX L
.SH NAME
mendex \- Japanese index processor
.SH SYNOPSIS
\fBmendex\fR [-ilqrcgEJSU] [\fB-s\fI sty\fR] [\fB-d\fI dic\fR] [\fB-o\fI ind\fR] [\fB-d\fI dic\fR] [\fB-t\fI log\fR] [\fB-p\fI no\fR] [\fB-I\fI enc\fR] [\fB--\fR] [\fI idx0 idx1 idx2 ...\fR]
.SH DESCRIPTION
.PP
The program \fImendex\fR is a general purpose hierarchical index generator;
it accepts one or more input files (\fI.idx\fR; often produced by a text
formatter such as \*(LX, sorts the entries, and produces an output file
which can be formatted. It is almost compatible with \fImakeindex\fR, and
さらに「読み」の扱いの手間を減らすように特殊化されています。
.RE
The formats of the input and output files are specified in a style file.
また、辞書ファイルを与えることにより、索引中の熟語の読みが登録されます。
.RE
The index can have up to three levels (0, 1, and 2) of subitem nesting.
.SH OPTIONS
.PP
.TP 10
\fB-h\fR, \fB--help\fR
Show summary of options.
.TP 10
\fB-i\fR
Take input from stdin, even when index files are specified.
.TP 10
\fB-l\fR
Letter ordering; by default, word ordering is used.
.TP 10
\fB-q\fR
Quiet mode; send no message to \fIstderr\fR, except error
messages and warnings.
.TP 10
\fB-r\fR
Disable implicit page range formation; by default, three or
more successive pages are automatically abbreviated as a range
(e.g. 1\(em5).
.TP 10
\fB-c\fR
Compress intermediate blanks (ignoring leading and trailing
blanks and tabs). By default, blanks in the index key are retained.
.TP 10
\fB-g\fR
Make Japanese index head A\-line of the gojuon table (Japanese
syllabary) ; by default, all the characters in the gojuon table
are used.
.TP 10
\fB-f\fR
Force to output Kanji characters even non-existent in dictionaries.
.TP 10
\fB-s\fI sty\fR
Employ \fIsty\fR as the style file.
.TP 10
\fB-d\fI dic\fR
Employ \fIdic\fR as the dictionary file. The dictionary file is
composed of lists of <\fIkanji\fR\ \fIsyllables\fR>.
.TP 10
\fB-o\fI ind\fR
Employ \fIind\fR as the output index file. By default, the file
name is created by appending the extension \fIind\fR to the base
name of the first input file.
.TP 10
\fB-t\fI log\fR
Employ \fIlog\fR as the transcript file. By default, the file name
is created by appending the extension \fIilg\fR to the base name
of the first input file.
.TP 10
\fB-p\fI no\fR
Set the starting page number of the output index file to be
\fIno\fR. The argument \fIno\fR may be numerical or one of
the following: \fIany\fR, \fIodd\fR, \fIeven\fR.
.TP 10
\fB-E\fR
Set input/output kanji encoding to EUC.
.TP 10
\fB-J\fR
Set input/output kanji encoding to EUC.
.TP 10
\fB-S\fR
Set input/output kanji encoding to ShiftJIS.
.TP 10
\fB-U\fR
Set input/output kanji encoding to UTF-8.
.TP 10
\fB-I\fI enc\fR
Set internal encoding to \fIenc\fR. The argument \fIenc\fR
may be \fIeuc\fR(EUC-JP) or \fIutf8\fR(UTF-8).
.TP 10
\fB--\fR
以降はオプション文字列と解釈しません。

＝＝＝＝ここまでmendex.1.jaからコピペしてきて英訳＝＝＝＝
一部まだ英訳していないので、要修正
＝＝＝＝＝＝＝＝＝＝ここから未編集です＝＝＝＝＝＝＝＝＝＝

.SH "SEE ALSO"
The programs are documented fully by
.IR "The Rise and Fall of a Fooish Bar" ,
available via the Info system.
.SH AUTHOR
This manual page was written by Masayuki Hatta <mhatta@debian.or.jp>,
for the Debian GNU/Linux system (but may be used by others).
